apiVersion: agentgateway.ai/v1alpha1
kind: ModelServer
metadata:
  name: openai-gpt4o
spec:
  baseUrl: https://api.openai.com/v1
  provider: openai
  models:
    - gpt-4o
    - gpt-4o-mini
  auth:
    apiKeySecret:
      name: openai-api-key
      key: OPENAI_API_KEY
---
apiVersion: agentgateway.ai/v1alpha1
kind: MCPServer
metadata:
  name: commerce-api-auth0
spec:
  transport:
    type: http
    http:
      url: https://your-commerce-api.example.com/mcp
      # Enable authentication passthrough to forward Auth0 tokens
      backendAuth:
        passthrough: true
  tools:
    - name: get_product
      description: Retrieves product information by product ID
      inputSchema:
        type: object
        properties:
          productId:
            type: string
            description: The unique identifier of the product
        required:
          - productId
    
    - name: list_products
      description: Lists all available products with optional filtering
      inputSchema:
        type: object
        properties:
          category:
            type: string
            description: Optional category filter
          limit:
            type: integer
            description: Maximum number of products to return
            default: 10
    
    - name: search_products
      description: Search for products by name or description
      inputSchema:
        type: object
        properties:
          query:
            type: string
            description: Search query string
          max_results:
            type: integer
            description: Maximum number of results to return
            default: 20
        required:
          - query
    
    - name: get_product_availability
      description: Check product availability and stock levels
      inputSchema:
        type: object
        properties:
          productId:
            type: string
            description: The unique identifier of the product
          location:
            type: string
            description: Optional location/warehouse code
        required:
          - productId
    
    - name: get_product_reviews
      description: Get customer reviews for a specific product
      inputSchema:
        type: object
        properties:
          productId:
            type: string
            description: The unique identifier of the product
          rating_filter:
            type: integer
            description: Optional filter by star rating (1-5)
            minimum: 1
            maximum: 5
        required:
          - productId
    
    - name: add_to_cart
      description: Add a product to the shopping cart
      inputSchema:
        type: object
        properties:
          productId:
            type: string
            description: The unique identifier of the product
          quantity:
            type: integer
            description: Quantity to add to cart
            default: 1
            minimum: 1
        required:
          - productId
    
    - name: get_cart
      description: Retrieve current shopping cart contents
      inputSchema:
        type: object
        properties: {}
    
    - name: update_cart_item
      description: Update quantity of an item in the cart
      inputSchema:
        type: object
        properties:
          cartItemId:
            type: string
            description: The unique identifier of the cart item
          quantity:
            type: integer
            description: New quantity (0 to remove item)
            minimum: 0
        required:
          - cartItemId
          - quantity
    
    - name: remove_from_cart
      description: Remove an item from the shopping cart
      inputSchema:
        type: object
        properties:
          cartItemId:
            type: string
            description: The unique identifier of the cart item to remove
        required:
          - cartItemId
    
    - name: get_user_orders
      description: Get order history for the authenticated user
      inputSchema:
        type: object
        properties:
          limit:
            type: integer
            description: Maximum number of orders to return
            default: 10
          status:
            type: string
            description: Optional filter by order status
            enum:
              - pending
              - processing
              - shipped
              - delivered
              - cancelled
    
    - name: get_order_details
      description: Get detailed information about a specific order
      inputSchema:
        type: object
        properties:
          orderId:
            type: string
            description: The unique identifier of the order
        required:
          - orderId
    
    - name: track_order
      description: Get tracking information for an order
      inputSchema:
        type: object
        properties:
          orderId:
            type: string
            description: The unique identifier of the order
        required:
          - orderId
    
    - name: create_order
      description: Create a new order from cart contents
      inputSchema:
        type: object
        properties:
          shipping_address:
            type: object
            properties:
              street:
                type: string
              city:
                type: string
              state:
                type: string
              zip:
                type: string
              country:
                type: string
            required:
              - street
              - city
              - state
              - zip
              - country
          payment_method:
            type: string
            description: Payment method identifier
        required:
          - shipping_address
          - payment_method
---
apiVersion: agentgateway.ai/v1alpha1
kind: Agent
metadata:
  name: commerce-assistant-auth0
spec:
  model: gpt-4o
  modelServer: openai-gpt4o
  mcpServers:
    - commerce-api-auth0
  systemPrompt: |
    You are a helpful e-commerce shopping assistant with access to a product catalog and order management system.
    
    You can help users:
    - Search and browse products
    - Get detailed product information and reviews
    - Check product availability
    - Manage shopping carts (add, update, remove items)
    - View order history and track orders
    - Place new orders
    
    When users ask about products, always provide relevant details including pricing, availability, and customer ratings when available.
    Be proactive in suggesting related products or alternatives when appropriate.
    For order-related queries, always verify the user's authentication status and handle their personal information securely.
    
    Important: All API calls are authenticated using the user's Auth0 token, which is automatically forwarded by the gateway.
    This ensures that users can only access their own cart and order information.
